FROM webdevops/go-crond:master-alpine

ENV POSTGRES_DATABASE **None**
ENV POSTGRES_BACKUP_ALL **None**
ENV POSTGRES_HOST **None**
ENV POSTGRES_PORT 5432
ENV POSTGRES_USER **None**
ENV POSTGRES_PASSWORD **None**
ENV POSTGRES_EXTRA_OPTS ''

ENV SCHEDULE **None**

ENV BACKUP_DIR="/backups"
ENV BACKUP_SUFFIX=".sql.gz"
ENV BACKUP_KEEP_DAYS=7
ENV BACKUP_KEEP_WEEKS=4
ENV BACKUP_KEEP_MONTHS=6
ENV BACKUP_KEEP_MINS=1440

ADD run.sh run.sh
ADD backup.sh backup.sh

VOLUME ${BACKUP_DIR}

ENTRYPOINT []
CMD ["sh", "run.sh"]